name: Flask Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy necessary files
        run: |
          # Copy any necessary files to the expected locations, if needed
          cp -r artifacts ./artifacts  # Adjust this based on your project structure
          
      - name: Run pytest
        run: |
          export PYTHONPATH=${{ github.workspace }}
          pytest